package com.cs324.backend.api;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Result of a distributed client job, returned to the requesting client and
 * kept in the coordinator's history for the Server Manager dashboard.
 *
 * <p>Carries the unique task ID generated by the coordinator, the client that
 * submitted the job, the job type, the number of segments the task was split
 * into, and the ordered list of worker nodes that processed each segment. The
 * final answer is compiled by the coordinator from the workers' partial
 * results, so the balance between lowest-JAC worker selection and synchronised
 * task completion stays visible end to end.</p>
 */
public final class TaskResult implements Serializable {
    private static final long serialVersionUID = 1L;

    private final String taskId;
    private final String clientId;
    private final String jobType;
    private final long result;
    private final int segmentCount;
    private final List<Integer> workerIds;
    private final int coordinatorId;
    private final long startedAtMillis;
    private final long completedAtMillis;

    public TaskResult(String taskId, String clientId, String jobType, long result,
                      int segmentCount, List<Integer> workerIds, int coordinatorId,
                      long startedAtMillis, long completedAtMillis) {
        this.taskId = taskId;
        this.clientId = clientId;
        this.jobType = jobType;
        this.result = result;
        this.segmentCount = segmentCount;
        this.workerIds = new ArrayList<>(workerIds);
        this.coordinatorId = coordinatorId;
        this.startedAtMillis = startedAtMillis;
        this.completedAtMillis = completedAtMillis;
    }

    public String getTaskId() {
        return taskId;
    }

    public String getClientId() {
        return clientId;
    }

    public String getJobType() {
        return jobType;
    }

    public long getResult() {
        return result;
    }

    public int getSegmentCount() {
        return segmentCount;
    }

    /** Worker nodes that processed each segment, in assignment order. */
    public List<Integer> getWorkerIds() {
        return workerIds;
    }

    public int getCoordinatorId() {
        return coordinatorId;
    }

    public long getStartedAtMillis() {
        return startedAtMillis;
    }

    public long getCompletedAtMillis() {
        return completedAtMillis;
    }

    @Override
    public String toString() {
        return "TaskResult{taskId=" + taskId + ", client=" + clientId + ", job=" + jobType
                + ", segments=" + segmentCount + ", workers=" + workerIds + ", result=" + result + "}";
    }
}